export const TIMEZONES = [
  { value: 'Asia/Colombo', label: 'Asia/Colombo — Sri Lanka (default)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata — India' },
  { value: 'Asia/Dhaka', label: 'Asia/Dhaka — Bangladesh' },
  { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu — Nepal' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi — Pakistan' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai — UAE' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore' },
  { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala Lumpur — Malaysia' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok — Thailand' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo — Japan' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai — China' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong Kong' },
  { value: 'Europe/London', label: 'Europe/London — UK' },
  { value: 'Europe/Paris', label: 'Europe/Paris' },
  { value: 'America/New_York', label: 'America/New York — US East' },
  { value: 'America/Los_Angeles', label: 'America/Los Angeles — US West' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney' },
  { value: 'UTC', label: 'UTC' },
];
